### PR TITLE
Static baseline report

### PR DESCRIPTION
**Pull request by lrasmus**
Optional feature (set in config/popHealth.yml by changing show_measure_baseline_report to true) to allow comparing measure results against one or more static baselines in a single formatted display.  

Loading is done via the command line:
`rake import:measure_baselines[json_path,clear_existing]`
Where clear_existing allows you to clear out all existing baselines before loading the new file.

An example baseline configuration file can be found at:
`test/fixtures/measure_baselines.json`

### CODE REVIEW

**Comment by lrasmus** [comment]
Example of a configured report with multiple sources.

image

**Comment by johnrancourt** [comment]
Luke - Break a leg at OSEHRA tomorrow. Wish I could be there. Hope all in the community are well! John Rancourt
(202) 746-7462
johnrancourt@yahoo.com

**Comment by petercyli** [comment]
I'm trying to understand the example measure_baselines.json file.  For each source you specify multiple measures.  
Q1 - What is measure_id? Is it the cms_id?
Q2 - Any reason why for a given source you have same measure_id repeated multiple time. 
Q3 - Meaning of calculation_date

**Comment by lrasmus** [comment]
Peter, thanks for the review.  To answer your questions:
1. It is hqmf_id.  Should I rename the field to better reflect this?
2. A measure_id could be duplicated if it has sub-parts, or if from a source you have different baselines for different date ranges (e.g., the 2014 baseline, the 2015 baseline).
3. This is more for internal tracking/provenance purposes - it's supposed to be a date (specified manually by the person creating the baseline file) that the baseline data was created.  It is used as a tie-breaker if by some reason you have loaded a baseline for the same measure with the same start/end date (e.g., I uploaded the wrong 2014 baseline data, and so I upload it and have a more recent calculation_date).

**Pull request merged**
