### PR TITLE
Handle if bundle license is nil

### PR DESCRIPTION
**Pull request by lrasmus**
Fringe situation, but with custom bundles the license isn't always set and that causes the app to crash when you try and register a new user.  This guards against the crash, while allowing license to still come back as nil from the getter.

### CODE REVIEW

**Comment by petercyli** [comment]
Can you indicate that the pull request passes the Travis CI tests?
Thanks.

**Comment by lrasmus** [comment]
Will fix - sorry, I didn't notice Travis didn't run.

**Comment by lrasmus** [comment]
Travis CI is now passing.

**Comment by petercyli** [comment]
Looks good for merge.

**Pull request merged**
