### PR TITLE
Patient record update logic

### PR DESCRIPTION
**Pull request by smc-ssiddiqui**
- Uploading same patients (with the same MRN) will update clinical data for all sections
- Added Social History data elements to patient chart
- Fix import bug for null provider information in the XML

### CODE REVIEW

**Comment by eedrummer** [comment]
Do we have tests to show that this works now?

**Comment by eedrummer** [comment]
Looks good.

**Comment by osehr-agent** [comment]
Hi Andy,

 

I haven’t tested the #11.  However, I believe the Alabama team has tested the pull request as described in the test plan - http://issues.osehra.org/browse/POP-281?filter=11300.  I will check with them.

 

I will also test the pull request myself tomorrow.

 

Thanks.

Peter

**Comment by petercyli** [comment]
Test passed based on the test plan - see JIRA ticket - http://issues.osehra.org/browse/POP-281?filter=11300. for detail.

Good to merge.

**Pull request merged**
