### PR TITLE
Fixes issue with Measures API not working

### PR DESCRIPTION
**Pull request by aaldrich**
The current measures api does not work. Any calls to it return "LoadError (Unable to autoload constant Measure, expected /home/vagrant/popHealth/lib/hds/measure.rb to define it):"

This is because the lib/hds/measure.rb is conflicting with the MeasuresController naming convention. The isn't an ideal fix but the namespacing from health data standards is not correct, however it does fix the issue and allow the Measures API to work again.

### CODE REVIEW

**Comment by chelope** [comment]
Could you please specify in which service you get the error? I have tested the services

-GET /api/measures
-GET /api/measures/40280381-503F-A1FC-0150-DE8350A220C3

But  I didn't get an error.

**Comment by petercyli** [comment]
I'm a little puzzled by this pull request.  Basically, you are renaming the measure.rb located in the lib/hds directory to cms_measure.rb and changing the references to measure.rb in two source files  in the "require" statement to cms_measure.rb.   Not sure why renaming would fix the problem.

**Comment by petercyli** [comment]
I also verified that Get /api/measures  works on pophealth-demo.osehra.org.   So it is not clear the changes you are asking make sense.

**Comment by aaldrich** [comment]
@petercyli I get an error on this call using the latest master code base. It never even hits the controller because of the error I mentioned. This was from a fresh install. 

I don't love the changes I made but it doesn't work without them. I'm not sure why you aren't getting them. Could you possibly pull down a fresh copy of master and try it? I was using the 5.1 install instructions and followed them exactly.

localhost:8080/api/measures?measure_ids[]=40280382-5ABD-FA46-015B-4981E40B37E6&measure_ids[]=40280382-5ABD-FA46-015B-1AFE205E2890&measure_ids[]=40280382-5ABD-FA46-015B-1ABD1D0427DE&measure_ids[]=40280382-5ABD-FA46-015B-497DD1E937DA&measure_ids[]=40280382-5ABD-FA46-015B-4981E40B37E6&measure_ids[]=40280382-5ABD-FA46-015B-498DF1243816&measure_ids[]=40280382-5ABD-FA46-015B-498DF1243816&measure_ids[]=40280382-5ABD-FA46-015B-1B7C6BB929D0&measure_ids[]=40280382-5B4D-EEBC-015B-5D99505001EA&measure_ids[]=40280382-5ABD-FA46-015B-49A568C83894&measure_ids[]=40280382-5ABD-FA46-015B-49B5B1E638E3

**Comment by petercyli** [comment]
Today I build a new pophealth install from scratch using ubuntu 16.04.  After the installation, I was able to query the /api/measures and return a list of all measures.  Once I login, I could issue the following request:
http://198.61.149.207/api/measures?measure_ids[]=40280382-5ABD-FA46-015B-4981E40B37E6 and receive the measure description.  Not sure why you stuff didn't work.

**Comment by aaldrich** [comment]
@petercyli that is strange, not sure what I did wrong. Thanks for trying to reproduce, I think we can just close this PR then since it's not needed. Do you agree?

**Comment by petercyli** [comment]
Will not accept the pull request due to inability to reproduce the problem.

**Pull request closed without merging**
